export const ADD_DECK = "ADD_DECK"
export const ADD_CARD = "ADD_CARD"
export const REPLACE_CARD = "REPLACE_CARD"
export const SEARCH = "SEARCH"
export const LOAD_DATA = "LOAD_DATA"
export const CREATE_STUDY = "CREATE_STUDY"
export const NEXT_CARD = "NEXT_CARD"
export const END_STUDY = "END_STUDY"